---
####################################################################################
# Ensure the session the netwfoundry token is initilized for the instacne creation #
# tasks, wchich include tasks to create Edge Routers on the NetFoundry Network.    #
####################################################################################

- include_tasks: network.yml
  tags:
    - vnc

- include_tasks: instance.yml
  when: netfoundry_network
  tags:
    - instance