---
######################################################################################
# Find all with the tunnel option enabled and create a list (router type endpoints)  #
# Also, update router endpoints with the same attributes, bc they are not by defualt #
######################################################################################
- set_fact:
    endpoints: "{{ netfoundry_network.network.customer_edge_routers | json_query('[? tunnelerEnabled == `true`].{name: name, attributes: attributes}') }}"
  tags:
    - create

#- name: Update endpoints type router with the same atributes as hosted edge routers of the same name
#  netfoundry_endpoint:
#    name: "{{ item.name }}"
#    attributes: "{{ item.attributes }}"
#    network: "{{ netfoundry_network.network }}"
#  loop: "{{ endpoints }}"
#  tags: 
#    - create

###################################
# Configure Services and AppWans  #
###################################
- name: Netcat udp service per region for one az
  netfoundry_service_advanced:
    name: "udp-{{ item.name }}"
    endpoints: 
    - "@{{ item.name }}"
    attributes: 
    - "#{{ item.name | split('.') | last }}"
    clientHosts: 
    - 192.168.100.111
    clientPorts: 
    - 5050
    - 700:800
    clientProtocols: 
    - udp
    network: "{{ netfoundry_network.network }}"
  loop: "{{ endpoints }}"
  when: item.name is regex("1")
  retries: 2
  tags:
    - create

- name: Netcat tcp service per region for one az
  netfoundry_service_advanced:
    name: "tcp-{{ item.name }}"
    endpoints: 
    - "@{{ item.name }}"
    attributes: 
    - "#{{ item.name | split('.') | last }}"
    clientHosts: 
    - 10.1.1.5
    clientPorts: 
    - 8080
    - 500:600
    clientProtocols: 
    - tcp
    network: "{{ netfoundry_network.network }}"
  loop: "{{ endpoints }}"
  when: item.name is regex("1")
  retries: 2
  tags:
    - create

- name: Collect the Network Info again after addition of services
  netfoundry_info:
    network: "{{ network_prefix }}"
    inventory: True
    session: "{{ netfoundry_organization.session }}"
  register: netfoundry_network
  tags:
    - create

#####################################################################################
# Find all with the tunnel option enabled and create a list (router type endpoints) #
#####################################################################################
- set_fact:
    services: "{{ netfoundry_network.network.services | json_query('[*].{name: name, srvc_attributes: attributes, endp_attributes: model.bindEndpointAttributes }') }}"
  tags:
    - create

- name: Create AppWan per service hosting az in a region
  netfoundry_appwan:
    name: "appwan.{{ item | regex_replace('#', '') }}"
    endpoints: "{{ endpoints | json_query('[*].attributes') | flatten | unique | difference(item) | select('search','1') }}"
    services: "{{ item }}"
    network: "{{ netfoundry_network.network }}"
  loop: "{{ services | json_query('[*].srvc_attributes') | flatten | unique }}"
  retries: 2
  tags:
    - create
