---
oci_regions:
  - name: us-ashburn-1
    cidr: 10.10.0.0/16
    subnet: 10.10.0.0/24
    az:
      - us-ashburn-ad-1
      - us-ashburn-ad-2
  - name: us-phoenix-1
    cidr: 10.11.0.0/16
    subnet: 10.11.0.0/24
    az:  
      - phx-ad-1
      - phx-ad-2